[package]
name = "chorechart"
version = "0.1.0"
authors = ["Esty Thomas <esty@healpay.com>"]
edition = "2018"

[dependencies]
csv = "1.0"
chrono = { version = "0.4.6", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "0.11"
